version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /opt/fabu-data/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - appnet

  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      FABU_DB_HOST: mongo
      FABU_BASE_URL: https://apps.icomecloud.com
      FABU_UPLOAD_DIR: /fabu/upload
    ports: 
      - "9898:9898"
    volumes:
      - /opt/fabu-data/upload:/fabu/upload
    depends_on:
      - mongo
    networks:
      - appnet

networks:
  appnet:
    driver:
      bridge


  
